### 1 heapq

In [13]:
import heapq

nums = [2, 3,5, 1, 54, 23, 132]
heap = []
for num in nums:
    heapq.heappush(heap, num)       # 加入堆

print(heap[0])                      # 只想获取最小值而不是弹出，使用heap[0]
print([heapq.heappop(heap) for _ in range(len(nums))])      # 堆排序结果

1
[1, 2, 3, 5, 23, 54, 132]


In [19]:
nums = [2, 3, 5, 1, 54, 23, 132]
heapq.heapify(nums)
print([heapq.heappop(nums) for _ in range(len(nums))])
nums.append(10)
print(nums)

[1, 2, 3, 5, 23, 54, 132]
[10]


In [22]:
nums1 = [32, 3, 5, 34, 54, 23, 132]
nums2 = [23, 2, 12, 656, 324, 23, 54]

ans = heapq.merge(nums1, nums2)
print(list(ans))        # [23, 2, 12, 32, 3, 5, 34, 54, 23, 132, 656, 324, 23, 54]
nums1 = sorted(nums1)
nums2 = sorted(nums2)

res = heapq.merge(nums1, nums2)
print(list(res))        # [2, 3, 5, 12, 23, 23, 23, 32, 34, 54, 54, 132, 324, 656]

[23, 2, 12, 32, 3, 5, 34, 54, 23, 132, 656, 324, 23, 54]
[2, 3, 5, 12, 23, 23, 23, 32, 34, 54, 54, 132, 324, 656]


In [10]:
list1 = [1, 3, 5, 2, 6, 8, 9, 3]

heapq.heappush(list1, 12)
print(list1)

heapq1 = heapq.heappop(list1)
print(heapq1)

list1.append(-1)
heapq2 = heapq.heappop(list1)
print(heapq2)
print(list1)

[1, 3, 5, 2, 6, 8, 9, 3, 12]
1
3
[-1, 2, 5, 3, 6, 8, 9, 12]


In [15]:
nums = [2, 43, 45, 23, 12]
heapq.heapify(nums)
print(heapq.heappop(nums))

print(nums)

2
[12, 23, 45, 43]


In [16]:
nums = [1, 2, 4, 5, 3]
heapq.heapify(nums)

heapq.heapreplace(nums, 23)
print([heapq.heappop(nums) for _ in range(len(nums))])

[2, 3, 4, 5, 23]


In [17]:
nums = []
for num in [1, 5, 20, 18, 10, 200]:
    heapq.heappush(nums, -num)
print(list(map(lambda x:-x, nums)))

[200, 18, 20, 1, 10, 5]


In [21]:
nums = [20, 5, 1, 18, 200, 10]
heapq.heapify(nums)
heapq.heappushpop(nums, 100)
print([heapq.heappop(nums) for _ in range(len(nums))])      # [5, 10, 18, 20, 100, 200]
print(nums)

[5, 10, 18, 20, 100, 200]
[]


In [25]:
st = "ansn"
print(set(st))
print(st[::-1])

{'n', 'a', 's'}
nsna


In [33]:
n = 10
n = -~n             # +1
print(n)            # 11
n = ~-n             # -1
print(n)            # 10

11
10
True


In [34]:
x, y = -1, 2
print((x^y)<0)          # True
x, y = 1, 2
print((x^y)<0)          # False

True
False


In [35]:
from sklearn.datasets import make_classification

X, y = make_classification(n_samples=6, n_classes=4, n_features=6, n_informative=5, n_redundant=1, n_clusters_per_class=1)
display(X, y)

array([[ 1.22319078, -1.49850244,  1.21268295, -2.4579291 ,  1.8448293 ,
        -0.77284074],
       [ 0.57395709, -0.18407656,  0.25629936, -0.28978995,  0.42072459,
        -0.99239633],
       [ 1.31687594, -1.16195757, -1.65477483, -0.19695368, -0.17760578,
        -0.66222763],
       [ 1.9253499 ,  1.41966124,  1.56094658, -0.03371532,  0.19000646,
        -0.93934389],
       [ 0.03768554,  0.45560503,  0.20187599, -1.332125  , -1.30952602,
        -0.37884942],
       [-1.50570795,  1.70595609, -0.60344891,  0.22887515, -3.08758302,
        -0.75110605]])

array([0, 2, 1, 0, 1, 3])

In [1]:
from collections import deque
st = "abcd"
list1 = [0, 1, 2, 3]
dlist1 = deque(st)
dlist2 = deque(list1)
dlist1.append(4)
dlist2.append('k')
print(dlist1)
print(dlist2)

deque(['a', 'b', 'c', 'd', 4])
deque([0, 1, 2, 3, 'k'])


In [3]:
print(-5%4)

3


: 

In [5]:
import numpy as np

list1 = [1, 2, 3, 4, 5, 6]
arr1 = np.array(list1).reshape(2, 3)
print(arr1)
print(np.mean(arr1, axis=0))

[[1 2 3]
 [4 5 6]]
[2.5 3.5 4.5]


In [ ]:
class Solution(object):
    def find132pattern(self, nums):
        N = len(nums)
        left_min = [float("inf")] * N
        for i in range(1, N):
            left_min[i] = min(left_min[i - 1], nums[i - 1])
        stack = []
        for j in range(N - 1, -1, -1):
            mask = float("-inf")
            while stack and stack[-1] < nums[j]:
                mask = stack.pop()
            if left_min[j] < mask:
                return True
            stack.append(nums[j])
        return False

In [6]:
list1 = [1,2,3,4,5,6,7,8,9]
nums = list1[2:]
print(nums)

[3, 4, 5, 6, 7, 8, 9]


In [9]:
import time
print(time.time())
time = time.localtime(time.time())
print(time.tm_year)

1682172566.856574
2023


In [12]:
a = 2020-1-1
print("a=", a)

a= 2018


In [13]:
str1 = "assd"
print(str1.find('a'))

0


In [ ]:
# 列表转二叉树
class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right


# 列表转二叉树
def List2Tree(nums: List) -> TreeNode:
    """ 由输入列表生成树，返回根节点 """
    q = []
    if not nums:
        return
    root = TreeNode(val=nums.pop(0))
    q.append(root)
    while q:
        curr = q.pop(0)
        if nums:
            if nums[0] != None:
                curr.left = TreeNode(val=nums.pop(0))
                q.append(curr.left)
            else:
                nums.pop(0)
        if nums:
            if nums[0] != None:
                curr.right = TreeNode(val=nums.pop(0))
                q.append(curr.right)
            else:
                nums.pop(0)
    return root

In [15]:
lt = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lt.index(2)

1

In [16]:
from sortedcontainers import SortedSet
set1 = SortedSet()
set1.add(10)
set1.add(2)
print(set1)

SortedSet([2, 10])


In [20]:
from collections import Counter
list1 = [1,2,2,1,11,1]
cou = Counter(list1)
print(cou)
print(cou.values())
print(list1.count(1))

Counter({1: 3, 2: 2, 11: 1})
dict_values([3, 2, 1])
3


In [22]:
values = [1, 1, 1,1]
print(all(value==1 for value in values))

True


In [25]:
from math import log
print(log(8, 2))

3.0


In [1]:
print(set("abababab"))

{'a', 'b'}


In [8]:
from itertools import pairwise

print(dict(pairwise('12345')))
PREVIOUS = dict(pairwise("croakc"[::-1]))
print(PREVIOUS)

{'1': '2', '2': '3', '3': '4', '4': '5'}
{'c': 'k', 'k': 'a', 'a': 'o', 'o': 'r', 'r': 'c'}


In [5]:
from itertools import count, pairwise
print(dict(pairwise("ABCDE")))
for i in count(10):
    if i == 20:
        break
    print(i)

{'A': 'B', 'B': 'C', 'C': 'D', 'D': 'E'}
10
11
12
13
14
15
16
17
18
19


In [6]:
print(bin(2))

0b10


In [6]:
import numpy as np
shape = (3, 3)
print(np.zeros(shape, dtype=int))
print(np.ones(shape, dtype=int))
print(np.arange(2, 10, dtype=int))
print(np.empty(shape, dtype=int))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[2 3 4 5 6 7 8 9]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [9]:
print(np.diag([1, 2, 3]))
print(np.eye(3))

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
import numpy as np


def operate_array(operate, x, y):
    if operate == '+':
        print('数组相加：')
        res = x + y
        print(res)
        print('数组相加：numpy方法：')
        res = np.add(x, y)
        print(res)
    elif operate == '-':
        print('数组相减:')
        res = x - y
        print(res)
        print('数组相减，numpy方法：')
        res = np.subtract(x, y)
        print(res)
    elif operate == '*':
        print('数组相乘，逐元素矩阵乘法：')
        res = x * y
        print(res)
        print('数组相乘，numpy方法：逐元素矩阵乘法：')
        res = np.multiply(x, y)
        print(res)
    elif operate == '/':
        print('数组相除，对应元素相除：')
        res = x / y
        print(res)
        print('数组相除，numpy方法：对应元素相除：')
        res = np.divide(x, y)
        print(res)


if __name__ == '__main__':
    x = np.array([[1, 2, 3], [4, 5, 6]])
    y = np.array([[4, 5, 6], [7, 8, 9]])

    operate_array('+', x, y)
    operate_array('-', x, y)
    operate_array('*', x, y)
    operate_array('/', x, y)

数组相加：
[[ 5  7  9]
 [11 13 15]]
数组相加：numpy方法：
[[ 5  7  9]
 [11 13 15]]
数组相减:
[[-3 -3 -3]
 [-3 -3 -3]]
数组相减，numpy方法：
[[-3 -3 -3]
 [-3 -3 -3]]
数组相乘，逐元素矩阵乘法：
[[ 4 10 18]
 [28 40 54]]
数组相乘，numpy方法：逐元素矩阵乘法：
[[ 4 10 18]
 [28 40 54]]
数组相除，对应元素相除：
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]]
数组相除，numpy方法：对应元素相除：
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]]


In [12]:
import numpy as np


if __name__ == '__main__':
    data = np.random.randint(0, 10, size=(10))
    print('输入数据: {}'.format(data))

    data_sum = np.sum(data)
    print('求和: {}'.format(data_sum))

    data_mean = np.mean(data)
    print('求平均: {}'.format(data_mean))

    data_std = np.std(data)
    print('求标准差: {}'.format(data_std))

    data_var = np.var(data)
    print('求方差: {}'.format(data_var))

    data_min = np.min(data)
    print('求最小值: {}'.format(data_min))

    data_max = np.max(data)
    print('求最大值: {}'.format(data_max))

    data_median = np.median(data)
    print('求中位数: {}'.format(data_median))

    data_unique = np.unique(data)
    print('找出数组中所有不同的值，并按从小打大排序： {}'.format(data_unique))

输入数据: [2 5 0 6 7 6 5 3 8 2]
求和: 44
求平均: 4.4
求标准差: 2.4166091947189146
求方差: 5.840000000000001
求最小值: 0
求最大值: 8
求中位数: 5.0
找出数组中所有不同的值，并按从小打大排序： [0 2 3 5 6 7 8]


In [14]:
# 可以通过数组转为矩阵
# 矩阵 b :
# <code>
# [[3 9 4]
#  [6 7 9]
#  [3 5 7]]
# </code>

# b的转置矩阵为：
# <code>
# [[3 6 3]
#  [9 7 5]
#  [4 9 7]]
# </code>

# b的逆矩阵：
# <code>
# [[-0.04597701  0.49425287 -0.6091954 ]
#  [ 0.17241379 -0.10344828  0.03448276]
#  [-0.10344828 -0.13793103  0.37931034]]
# </code>

import numpy as np


if __name__ == '__main__':
    a = np.random.randint(0, 10, size=(3, 3))
    matrix_b = np.matrix(a)
    print(matrix_b)
    print(matrix_b.T)
    print(matrix_b.I)

[[5 9 5]
 [3 2 1]
 [9 9 9]]
[[5 3 9]
 [9 2 9]
 [5 1 9]]
[[-1.25000000e-01  5.00000000e-01  1.38888889e-02]
 [ 2.50000000e-01 -2.77555756e-17 -1.38888889e-01]
 [-1.25000000e-01 -5.00000000e-01  2.36111111e-01]]


In [15]:
import numpy as np


def random_sample(array, num):
    if num <= len(array):
                                            
        return np.random.choice(array, num)
    else:
        return None


if __name__ == '__main__':
    a = [i for i in range(10)]
    print('输入的数据：{}'.format(a))

    ret = random_sample(a, 11)
    assert ret is None
    print('随机抽样个数不能超过原始数组大小')

    ret = random_sample(a, 2)
    assert len(ret) == 2
    print('随机抽样结果：{}'.format(ret))

输入的数据：[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
随机抽样个数不能超过原始数组大小
随机抽样结果：[1 8]


In [17]:
import numpy as np


def test():
    x = np.array([1, 2, 3, -1, 5])
    y = np.ma.masked_array(x, mask=[0, 0, 0, 1, 0])
    print('查看y的值: ')
    for idx, val in enumerate(y):
        print('y[{}] = {}'.format(idx, val))

    assert type(y[3]) is np.ma.core.MaskedConstant

    print('y的平均值: {}'.format(np.mean(y)))
    assert np.mean(y) == 2.75


if __name__ == '__main__':
    test()

查看y的值: 
y[0] = 1
y[1] = 2
y[2] = 3
y[3] = --
y[4] = 5
y的平均值: 2.75


In [19]:
import numpy as np


def create_mask_array(array_a, mask_list):
    mask = np.zeros(len(array_a), dtype=int)
    for i in mask_list:
        mask[i] = 1

    y = np.ma.array(array_a, mask=mask)
    return y


if __name__ == '__main__':
    a = np.random.randint(0, 10, size=(10))
    b = create_mask_array(a, [0, 1, 2, 3, 4])
    assert np.mean(b) == np.mean(a[5:])

In [20]:
import numpy as np


def create_condition_mask_array(array_a, val):
    mask = np.zeros(len(array_a), dtype=int)
    for i in range(len(array_a)):
        if array_a[i] >= val:
            mask[i] = 1

    y = np.ma.array(array_a, mask=mask)
    return y


if __name__ == '__main__':
    a = np.random.randint(0, 10, size=(10))
    b = create_condition_mask_array(a, 5)

    na = [x for x in a if x < 5]
    nb = [x for x in b if type(x) is not np.ma.core.MaskedConstant]

    assert na == nb