In [1]:
import torch
import torch.nn.functional as F
from torch import nn

In [6]:
from turtle import forward


class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(784, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        out = F.relu(self.hidden(x))
        out = self.output(out)
        return out

In [11]:
X = torch.rand(2, 784)
net = MLP()
print(net)
# print(net(X))
print(net.hidden.weight.data.shape)
print(net.hidden.bias.data.shape)

MLP(
  (hidden): Linear(in_features=784, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)
torch.Size([256, 784])
torch.Size([256])


In [43]:
tensor01 = torch.rand(1, 4)
print(tensor01)
norm1 = torch.norm(tensor01, p=1)
print(norm1)
norm2 = torch.norm(tensor01, p=2)
print(norm2)
norm3 = torch.norm(tensor01, p=1, dim=0).sum()
print(norm3)
norm4 = torch.sum(torch.pow(tensor01, 2))
print(norm4)
norm5 = torch.norm(tensor01, p=2, dim=0).sum()
print(norm5)

tensor([[0.4048, 0.7975, 0.2387, 0.1865]])
tensor(1.6275)
tensor(0.9443)
tensor(1.6275)
tensor(0.8917)
tensor(1.6275)


In [39]:
current = torch.tensor([1, 1, 1, 1, 1])
ans = torch.full(current.shape, float("inf"))
selected = torch.tensor([1, 0, 1, 0, 1])
diff = current & ~selected
print(diff)
alpha = torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5])
ans[diff.nonzero().flatten()] = 2
print(ans)

tensor([0, 1, 0, 1, 0])
tensor([inf, 2., inf, 2., inf])


In [45]:
import torch
tensor01 = torch.arange(9, dtype=torch.float) - 4
tensor02 = tensor01.reshape((3, 3))
print(torch.norm(tensor01))     # tensor(7.7460)
print(torch.norm(tensor02))     # tensor(7.7460)

tensor(7.7460)
tensor(7.7460)


In [46]:
print(torch.norm(tensor01, float('inf')))       # tensor(4.)
print(torch.norm(tensor02, float('inf')))       # tensor(4.)

tensor(4.)
tensor(4.)


In [49]:
print(torch.norm(tensor01, p=1))       # tensor(20.)
print(torch.norm(tensor02, p=1))       # tensor(20.)

tensor(20.)
tensor(20.)


In [50]:
print(torch.norm(tensor01, p=0))       # tensor(8.)
print(torch.norm(tensor02, p=0))       # tensor(8.)

tensor(8.)
tensor(8.)


In [51]:
tensor03 = torch.tensor([[1, 2, 3], [-1, 1, 4]], dtype=torch.float)
print(torch.norm(tensor03, dim=0))          # tensor([1.4142, 2.2361, 5.0000])
print(torch.norm(tensor03, dim=1))          # tensor([3.7417, 4.2426])
print(torch.norm(tensor03, p=1, dim=1))     # tensor([6., 6.])

tensor([1.4142, 2.2361, 5.0000])
tensor([3.7417, 4.2426])
tensor([6., 6.])


In [56]:
tensor04 = torch.arange(8, dtype=torch.float).reshape(2, 2, 2)
print(torch.norm(tensor04, dim=(1, 2)))             # tensor([ 3.7417, 11.2250])
print(torch.norm(tensor04[0, :, :]), torch.norm(tensor04[1, :, :]))     # tensor(3.7417) tensor(11.2250)

tensor([[[0., 1.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]]])
tensor([ 3.7417, 11.2250])
tensor(3.7417) tensor(11.2250)


In [57]:
tensor05 = torch.rand((2, 3, 4))
norm1 = torch.norm(tensor05, dim=1, keepdim=True)
norm2 = torch.norm(tensor05, dim=1, keepdim=False)
print(tensor05.shape)           # torch.Size([2, 3, 4])
print(norm1.shape)              # torch.Size([2, 1, 4])
print(norm2.shape)              # torch.Size([2, 4])

torch.Size([2, 3, 4])
torch.Size([2, 1, 4])
torch.Size([2, 4])


In [63]:
a = torch.tensor([[1, 2],
	 [3, 4]])
	 
index = torch.tensor([[1],[0]])

c = torch.gather(a, dim=1, index=index)
print(c)

tensor([[2],
        [3]])


In [60]:
t = torch.tensor([[1, 2], [3, 4]])
index = torch.tensor([[0, 0], [1, 0]])
print(torch.gather(t, dim=1, index=index))

tensor([[1, 1],
        [4, 3]])


In [65]:
t2 = torch.arange(40).reshape(4, 10)
index = torch.tensor([[2, 3], [6, 7], [0, 1], [4, 5]])
print(torch.gather(t2, dim=1, index=index))

tensor([[ 2,  3],
        [16, 17],
        [20, 21],
        [34, 35]])
