In [1]:
import torch
import torch.nn.functional as F
from torch import nn

In [6]:
from turtle import forward


class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(784, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        out = F.relu(self.hidden(x))
        out = self.output(out)
        return out

In [11]:
X = torch.rand(2, 784)
net = MLP()
print(net)
# print(net(X))
print(net.hidden.weight.data.shape)
print(net.hidden.bias.data.shape)

MLP(
  (hidden): Linear(in_features=784, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)
torch.Size([256, 784])
torch.Size([256])


In [43]:
tensor01 = torch.rand(1, 4)
print(tensor01)
norm1 = torch.norm(tensor01, p=1)
print(norm1)
norm2 = torch.norm(tensor01, p=2)
print(norm2)
norm3 = torch.norm(tensor01, p=1, dim=0).sum()
print(norm3)
norm4 = torch.sum(torch.pow(tensor01, 2))
print(norm4)
norm5 = torch.norm(tensor01, p=2, dim=0).sum()
print(norm5)

tensor([[0.4048, 0.7975, 0.2387, 0.1865]])
tensor(1.6275)
tensor(0.9443)
tensor(1.6275)
tensor(0.8917)
tensor(1.6275)


In [39]:
current = torch.tensor([1, 1, 1, 1, 1])
ans = torch.full(current.shape, float("inf"))
selected = torch.tensor([1, 0, 1, 0, 1])
diff = current & ~selected
print(diff)
alpha = torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5])
ans[diff.nonzero().flatten()] = 2
print(ans)

tensor([0, 1, 0, 1, 0])
tensor([inf, 2., inf, 2., inf])


In [45]:
import torch
tensor01 = torch.arange(9, dtype=torch.float) - 4
tensor02 = tensor01.reshape((3, 3))
print(torch.norm(tensor01))     # tensor(7.7460)
print(torch.norm(tensor02))     # tensor(7.7460)

tensor(7.7460)
tensor(7.7460)


In [46]:
print(torch.norm(tensor01, float('inf')))       # tensor(4.)
print(torch.norm(tensor02, float('inf')))       # tensor(4.)

tensor(4.)
tensor(4.)


In [49]:
print(torch.norm(tensor01, p=1))       # tensor(20.)
print(torch.norm(tensor02, p=1))       # tensor(20.)

tensor(20.)
tensor(20.)


In [50]:
print(torch.norm(tensor01, p=0))       # tensor(8.)
print(torch.norm(tensor02, p=0))       # tensor(8.)

tensor(8.)
tensor(8.)


In [51]:
tensor03 = torch.tensor([[1, 2, 3], [-1, 1, 4]], dtype=torch.float)
print(torch.norm(tensor03, dim=0))          # tensor([1.4142, 2.2361, 5.0000])
print(torch.norm(tensor03, dim=1))          # tensor([3.7417, 4.2426])
print(torch.norm(tensor03, p=1, dim=1))     # tensor([6., 6.])

tensor([1.4142, 2.2361, 5.0000])
tensor([3.7417, 4.2426])
tensor([6., 6.])


In [56]:
tensor04 = torch.arange(8, dtype=torch.float).reshape(2, 2, 2)
print(torch.norm(tensor04, dim=(1, 2)))             # tensor([ 3.7417, 11.2250])
print(torch.norm(tensor04[0, :, :]), torch.norm(tensor04[1, :, :]))     # tensor(3.7417) tensor(11.2250)

tensor([[[0., 1.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]]])
tensor([ 3.7417, 11.2250])
tensor(3.7417) tensor(11.2250)


In [57]:
tensor05 = torch.rand((2, 3, 4))
norm1 = torch.norm(tensor05, dim=1, keepdim=True)
norm2 = torch.norm(tensor05, dim=1, keepdim=False)
print(tensor05.shape)           # torch.Size([2, 3, 4])
print(norm1.shape)              # torch.Size([2, 1, 4])
print(norm2.shape)              # torch.Size([2, 4])

torch.Size([2, 3, 4])
torch.Size([2, 1, 4])
torch.Size([2, 4])


In [63]:
a = torch.tensor([[1, 2],
	 [3, 4]])
	 
index = torch.tensor([[1],[0]])

c = torch.gather(a, dim=1, index=index)
print(c)

tensor([[2],
        [3]])


In [60]:
t = torch.tensor([[1, 2], [3, 4]])
index = torch.tensor([[0, 0], [1, 0]])
print(torch.gather(t, dim=1, index=index))

tensor([[1, 1],
        [4, 3]])


In [65]:
t2 = torch.arange(40).reshape(4, 10)
index = torch.tensor([[2, 3], [6, 7], [0, 1], [4, 5]])
print(torch.gather(t2, dim=1, index=index))

tensor([[ 2,  3],
        [16, 17],
        [20, 21],
        [34, 35]])


In [68]:
t3 = torch.ones(2, 3, 4)
print(t3.size())
print(t3.dim())

torch.Size([2, 3, 4])
3


In [71]:
t4 = torch.zeros(2, 1, 2, 1, 2)
print(t4.size())        # torch.Size([2, 1, 2, 1, 2])
print(t4.dim())         # 5

t5 = torch.squeeze(t4)
print(t5.size())        # torch.Size([2, 2, 2])
print(t5.dim())         # 3

t6 = torch.squeeze(t4, 0)   
print(t6.size())            # torch.Size([2, 1, 2, 1, 2])
print(t6.dim())             # 5

t7 = torch.squeeze(t4, 1)
print(t7.size())            # torch.Size([2, 2, 1, 2])
print(t7.dim())             # 4

torch.Size([2, 1, 2, 1, 2])
5
torch.Size([2, 2, 2])
3
torch.Size([2, 1, 2, 1, 2])
5
torch.Size([2, 2, 1, 2])
4


In [73]:
t8 = torch.squeeze(t4, 2)
print(t8.size())            # torch.Size([2, 1, 2, 2])
print(t8.dim())             # 4

torch.Size([2, 1, 2, 2])
4


In [74]:
t9 = torch.squeeze(t4, 3)
print(t9.size())            # torch.Size([2, 1, 2, 2])
print(t9.dim())             # 4

torch.Size([2, 1, 2, 2])
4


In [76]:
t10 = torch.ones(2, 1, 1)
print(t10)                  # tensor([[[1.]], [[1.]]])
print(torch.squeeze(t10))   # tensor([1., 1.])

tensor([[[1.]],

        [[1.]]])
tensor([1., 1.])


In [78]:
t11 = torch.rand(2, 3)
print(t11)

torch.cat((t11, t11, t11), dim=0)

tensor([[0.1199, 0.9585, 0.4629],
        [0.0949, 0.6016, 0.1782]])


tensor([[0.1199, 0.9585, 0.4629],
        [0.0949, 0.6016, 0.1782],
        [0.1199, 0.9585, 0.4629],
        [0.0949, 0.6016, 0.1782],
        [0.1199, 0.9585, 0.4629],
        [0.0949, 0.6016, 0.1782]])

In [79]:
torch.cat((t11, t11, t11), dim=1)

tensor([[0.1199, 0.9585, 0.4629, 0.1199, 0.9585, 0.4629, 0.1199, 0.9585, 0.4629],
        [0.0949, 0.6016, 0.1782, 0.0949, 0.6016, 0.1782, 0.0949, 0.6016, 0.1782]])

In [82]:
t12 = torch.randn(10, 2)
t12
torch.chunk(t12, 4, dim=1)

(tensor([[-0.7073],
         [-0.0563],
         [-1.1048],
         [ 0.5760],
         [-0.4588],
         [ 1.4463],
         [-1.6160],
         [-0.5369],
         [-0.1279],
         [-0.2774]]),
 tensor([[ 0.9276],
         [ 1.3799],
         [ 0.2146],
         [-0.4910],
         [ 0.8314],
         [ 0.0367],
         [ 1.0240],
         [-0.1359],
         [ 0.0019],
         [ 0.6660]]))

In [85]:
t25 = torch.arange(0, 6)
print(t25)                          # tensor([0, 1, 2, 3, 4, 5])
t26 = torch.cumsum(t25, dim=0)
print(t26)                          # tensor([ 0,  1,  3,  6, 10, 15])
t27 = torch.cumsum(t25, dim=-1)
print(t27)                          # tensor([ 0,  1,  3,  6, 10, 15])

tensor([0, 1, 2, 3, 4, 5])
tensor([ 0,  1,  3,  6, 10, 15])
tensor([ 0,  1,  3,  6, 10, 15])


In [87]:
t28 = t25.view(2, 3)
print(t28)          # tensor([[0, 1, 2], [3, 4, 5]])

t29 = torch.cumsum(t28, dim=0)      
t31 = torch.cumsum(t28, dim=1)
t32 = torch.cumsum(t28, dim=-1)
print(t29)          # tensor([[0, 1, 2], [3, 5, 7]])
print(t31)          # tensor([[ 0,  1,  3], [ 3,  7, 12]])
print(t32)          # tensor([[ 0,  1,  3], [ 3,  7, 12]])

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 5, 7]])
tensor([[ 0,  1,  3],
        [ 3,  7, 12]])
tensor([[ 0,  1,  3],
        [ 3,  7, 12]])


In [88]:
t33 = torch.arange(0, 16).view(2, 2, 4)
print(t33)
t34 = torch.cumsum(t33, dim=0)
t35 = torch.cumsum(t33, dim=1)
t36 = torch.cumsum(t33, dim=2)
t37 = torch.cumsum(t33, dim=-1)
print(t34)
print(t35)
print(t36)
print(t37)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8, 10, 12, 14],
         [16, 18, 20, 22]]])
tensor([[[ 0,  1,  2,  3],
         [ 4,  6,  8, 10]],

        [[ 8,  9, 10, 11],
         [20, 22, 24, 26]]])
tensor([[[ 0,  1,  3,  6],
         [ 4,  9, 15, 22]],

        [[ 8, 17, 27, 38],
         [12, 25, 39, 54]]])
tensor([[[ 0,  1,  3,  6],
         [ 4,  9, 15, 22]],

        [[ 8, 17, 27, 38],
         [12, 25, 39, 54]]])
