本篇研究协方差矩阵的物理意义，参考自：[Preprocessing for deep learning: from covariance matrix to image whitening](https://hadrienj.github.io/posts/Preprocessing-for-deep-learning/)

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
A = np.array([[1, 3, 5], [5, 4, 1], [3, 8, 6]])
A

array([[1, 3, 5],
       [5, 4, 1],
       [3, 8, 6]])

In [5]:
np.cov(A, rowvar=False, bias=True)

array([[ 2.66666667,  0.66666667, -2.66666667],
       [ 0.66666667,  4.66666667,  2.33333333],
       [-2.66666667,  2.33333333,  4.66666667]])

In [8]:
def calculate_covariance(X):
    mean_x = np.mean(X, axis=0)
    len_x = X.shape[0]
    X = X - mean_x
    covariance = np.dot(X.T, X)/len_x
    return covariance

In [9]:
calculate_covariance(A)

array([[ 2.66666667,  0.66666667, -2.66666667],
       [ 0.66666667,  4.66666667,  2.33333333],
       [-2.66666667,  2.33333333,  4.66666667]])