In [1]:
import operator

a = 4
b = 3
print("The addition of number is:", operator.add(a, b))     # The addition of number is: 7

The addition of number is: 7


In [2]:
lst1 = ['', '1', '2', '3']
print(lst1[3])
lst2 = ["", "1", "2", "3"]
print(lst2[3])

3
3


In [7]:
thousands = ['', 'M', 'MM', 'MMM']
hundreds = ['', 'C', 'CC', 'CCC', 'CD', 'D', 'DC', 'DCC', 'DCCC', 'CM']
tens = ['', 'X', 'XX', 'XXX', 'XL', 'L', 'LX', 'LXX', 'LXXX', 'XC']
ones = ['', 'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX']

print(thousands[3])
print(hundreds[9])
print(tens[9])
print(ones[9])

MMM
CM
XC
IX


In [11]:
import numpy as np

arr1 = np.arange(12).reshape(4, 3)
print(arr1)
print(arr1[1, 2])
print(arr1[1][2])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
5
5


In [2]:
lst1 = ['a', 'dff', 'ddfffg', 'ujshshsu']
lst2 = [len(item) for item in lst1]
print(min(lst2))
['aaa', 'aaa', 'aaa']

1


In [29]:
def compare(target, lst):
    if sum(lst) < target or min(lst) > target:
        return 0
    else:
        return 1

compare(5, [1, 2, 3])

1

In [85]:
def findMedianSortedArrays(nums1, nums2):
    i, j = 0, 0
    nums = nums1[:]
    length1, length2 = len(nums1), len(nums2)
    while i < length2:
        while j < length1-1:
            if nums2[i] < nums1[0]:
                nums.insert(0, nums2[i])
                break
            elif nums2[i] > nums1[-1]:
                nums.append(nums2[i])
                break
            elif nums2[i] >= nums1[j] and nums2[i] <= nums1[j+1]:
                nums.insert(j+i+1, nums2[i])
                break
            j += 1
        else:
            nums += nums2[:]
            break
        i += 1
    length = length1 + length2
    print(nums)
    if length % 2:
        return nums[length//2]
    else:
        return (nums[length//2] + nums[length//2-1])/2


In [87]:
print(findMedianSortedArrays([3], [-2, -1]))

[3, -2, -1]
-2
