In [1]:
import operator

a = 4
b = 3
print("The addition of number is:", operator.add(a, b))     # The addition of number is: 7

The addition of number is: 7


In [2]:
lst1 = ['', '1', '2', '3']
print(lst1[3])
lst2 = ["", "1", "2", "3"]
print(lst2[3])

3
3


In [3]:
thousands = ['', 'M', 'MM', 'MMM']
hundreds = ['', 'C', 'CC', 'CCC', 'CD', 'D', 'DC', 'DCC', 'DCCC', 'CM']
tens = ['', 'X', 'XX', 'XXX', 'XL', 'L', 'LX', 'LXX', 'LXXX', 'XC']
ones = ['', 'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX']

print(thousands[3])
print(hundreds[9])
print(tens[9])
print(ones[9])

MMM
CM
XC
IX


In [4]:
import numpy as np

arr1 = np.arange(12).reshape(4, 3)
print(arr1)
print(arr1[1, 2])
print(arr1[1][2])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
5
5


In [5]:
lst1 = ['a', 'dff', 'ddfffg', 'ujshshsu']
lst2 = [len(item) for item in lst1]
print(min(lst2))
['aaa', 'aaa', 'aaa']

1


['aaa', 'aaa', 'aaa']

In [6]:
def compare(target, lst):
    if sum(lst) < target or min(lst) > target:
        return 0
    else:
        return 1

compare(5, [1, 2, 3])

1

In [7]:
def findMedianSortedArrays(nums1, nums2):
    i, j = 0, 0
    nums = nums1[:]
    length1, length2 = len(nums1), len(nums2)
    while i < length2:
        while j < length1-1:
            if nums2[i] < nums1[0]:
                nums.insert(0, nums2[i])
                break
            elif nums2[i] > nums1[-1]:
                nums.append(nums2[i])
                break
            elif nums2[i] >= nums1[j] and nums2[i] <= nums1[j+1]:
                nums.insert(j+i+1, nums2[i])
                break
            j += 1
        else:
            nums += nums2[:]
            break
        i += 1
    length = length1 + length2
    print(nums)
    if length % 2:
        return nums[length//2]
    else:
        return (nums[length//2] + nums[length//2-1])/2


In [8]:
print(findMedianSortedArrays([3], [-2, -1]))

[3, -2, -1]
-2


In [9]:
import torch
input = torch.arange(0, 6)
print(input)
print(input.shape)

tensor([0, 1, 2, 3, 4, 5])
torch.Size([6])


In [10]:
print(input.unsqueeze(0))
print(input.unsqueeze(0).shape)

tensor([[0, 1, 2, 3, 4, 5]])
torch.Size([1, 6])


In [11]:
print(input.unsqueeze(1))
print(input.unsqueeze(1).shape)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])
torch.Size([6, 1])


In [12]:
print(input.unsqueeze(-1))
print(input.unsqueeze(-1).shape)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])
torch.Size([6, 1])


In [17]:
u = [1, 2, -1, -2, -3, 4, 6]
u = torch.Tensor(u)
print(u)
u = u.unsqueeze(-1)
print(u)
u_abs_sorted = torch.sort(u.abs(), dim=0, descending=True).values
print(u_abs_sorted)

tensor([ 1.,  2., -1., -2., -3.,  4.,  6.])
tensor([[ 1.],
        [ 2.],
        [-1.],
        [-2.],
        [-3.],
        [ 4.],
        [ 6.]])
tensor([[6.],
        [4.],
        [3.],
        [2.],
        [2.],
        [1.],
        [1.]])


In [20]:
v = torch.arange(14)
v = v.unsqueeze(-1)
print(v)
k, batch = u.shape
s = torch.arange(k+1.0).view(-1, 1).to(v)
print(s)

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7]])


In [23]:
zeros = torch.zeros(1, batch).to(u)
print(zeros)

tensor([[0.]])


In [25]:
x = torch.Tensor([1, 2, -1, -2, -3, 4, 6])
ones = torch.ones_like(x)
print(ones)
print(torch.where(x >= 0, ones, -ones))

tensor([1., 1., 1., 1., 1., 1., 1.])
tensor([ 1.,  1., -1., -1., -1.,  1.,  1.])
