In [8]:
# 导入库
import numpy as np
from matplotlib import pyplot as plt

方法一：使用array函数，通过list创建数组对象

In [2]:
array1 = np.array([1, 2, 3, 4, 5])
array1

array([1, 2, 3, 4, 5])

In [5]:
array17 = np.random.randint(1, 100, (4, 6)).reshape((2, 3, 4))
array17

array([[[90, 35, 28, 31],
        [90, 34, 10, 20],
        [82, 36, 24, 25]],

       [[21, 23, 73, 75],
        [52, 95,  3, 33],
        [96, 73, 34, 57]]])

In [9]:
from matplotlib import pyplot as plt        # 导入库
array18 = plt.imread('01.jpg')              # 任意加载一张图片
array18

array([[[204, 204, 204],
        [105, 105, 105],
        [  3,   3,   3],
        ...,
        [  3,   4,   0],
        [  3,   4,   0],
        [  4,   5,   0]],

       [[206, 206, 206],
        [106, 106, 106],
        [  4,   4,   4],
        ...,
        [  6,   7,   2],
        [  6,   7,   2],
        [  6,   7,   2]],

       [[208, 208, 208],
        [108, 108, 108],
        [  6,   6,   6],
        ...,
        [ 10,  11,   6],
        [ 10,  11,   6],
        [  9,  10,   5]],

       ...,

       [[206, 207, 199],
        [112, 113, 105],
        [ 25,  26,  18],
        ...,
        [  9,  41,   2],
        [ 12,  37,   7],
        [ 15,  35,  10]],

       [[206, 207, 199],
        [113, 114, 106],
        [ 26,  27,  19],
        ...,
        [  9,  41,   2],
        [ 11,  36,   6],
        [ 14,  34,   9]],

       [[207, 208, 200],
        [113, 114, 106],
        [ 27,  28,  20],
        ...,
        [  9,  41,   2],
        [ 11,  36,   6],
        [ 14,  34,   9]]

In [11]:
array_one = np.arange(1, 100, 2)
array_two = np.random.rand(3, 4)
print(array_one.size, array_two.size)       # 50, 12

50 12


In [12]:
print(array_one.shape, array_two.shape)     # (50,) (3, 4)

(50,) (3, 4)


In [13]:
print(array_one.dtype, array_two.dtype)     # int32 float64

int32 float64


In [14]:
print(array_one.ndim, array_two.ndim)       # 1 2

1 2


In [15]:
array_three = np.arange(1, 100, 2, dtype=np.int8)
print(array_one.itemsize, array_two.itemsize, array_three.itemsize)     # 4 8 1

4 8 1


In [16]:
print(array_one.nbytes, array_two.nbytes, array_three.nbytes)       # 200 96 50

200 96 50


In [18]:
from typing import Iterable
print(isinstance(array_two.flat, np.ndarray), isinstance(array_two.flat, Iterable))     # False True

False True


In [19]:
array_four = array_one[:]
print(array_four.base is array_one, array_one.base is array_three)      # True False

True False


In [20]:
array19 = np.arange(10)
print(array19[0], array19[array19.size-1])      # 0 9
print(array19[-array19.size], array19[-1])      # 0 9

0 9
0 9


In [21]:
array20 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array20[2])       # [7 8 9]
print(array20[0][0], array20[-1][-1])       # 1 9

[7 8 9]
1 9


In [25]:
print(array20[:2, 1:])      # [[2 3] [5 6]]
print(array20[2])           # [7 8 9]
print(array20[2, :])        # [7 8 9]
print(array20[2:, :])       # [[7 8 9]]
print(array20[:, :2])       # [[1 2] [4 5] [7 8]]
print(array20[1, :2])       # [4 5]
print(array20[1:2, :2])     # [[4 5]]
print(array20[::2, ::2])    # [[1 3] [7 9]]
print(array20[::-2, ::-2])  # [[9 7] [3 1]]

[[2 3]
 [5 6]]
[7 8 9]
[7 8 9]
[[7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[4 5]
[[4 5]]
[[1 3]
 [7 9]]
[[9 7]
 [3 1]]


In [27]:
array21 = np.arange(10)
array21[[0, 1, -1]]     # array([0, 1, 9])

array([0, 1, 9])

In [31]:
array22 = np.array([[30, 20, 10], [40, 60, 50], [10, 90, 80]])
array22[[0, 2]]         # 取二维数组的第1行和第3行
array22[[0, 2], [1, 2]] # 取二维数组第1行第2列，第3行第3列的两个元素 array([20, 80])
array22[[0, 2], 1]      # 取二维数组第1行第2列，第3行第2列的两个元素 array([20, 90])

array([20, 90])

In [32]:
array24 = np.array([1, 2, 3, 4, 5, 5, 4, 3, 2, 1])
print(array24.sum())        # 30
print(array24.mean())       # 3.0
print(array24.max())        # 5
print(array24.min())        # 1
print(array24.std())        # 1.4142135623730951
print(array24.var())        # 2.0
print(array24.cumsum())     # [ 1  3  6 10 15 20 24 27 29 30]

30
3.0
5
1
1.4142135623730951
2.0
[ 1  3  6 10 15 20 24 27 29 30]


In [1]:
import numpy as np
array34 = np.array([0, 30, 45, 60, 90])
print(np.sin(array34*np.pi/180))

[0.         0.5        0.70710678 0.8660254  1.        ]


In [2]:
array35 = np.array([1.0, 5.55,  123,  0.567,  25.532]) 
print(np.around(array35))

[  1.   6. 123.   1.  26.]


In [3]:
array36 = np.array([10, 20, 30])
array37 = np.array([3, 5, 7])
print(np.mod(array36, array37))

[1 0 2]
