In [4]:
import numpy as np
array1 = np.random.randint(1, 10, 6)
print(array1)
print(np.where(array1 > 5, 1, -1))

[3 3 2 6 7 2]
[-1 -1 -1  1  1 -1]


In [5]:
np.where(array1 > 5)    # 获取满足条件得位置

(array([3, 4], dtype=int64),)

In [6]:
array1[np.where(array1 > 5)]

array([6, 7])

In [10]:
array2 = np.arange(6).reshape(2, 3)
print(array2)
print(np.argwhere(array2 % 2 == 0))
print(np.where(array2 % 2 == 0))

[[0 1 2]
 [3 4 5]]
[[0 0]
 [0 2]
 [1 1]]
(array([0, 0, 1], dtype=int64), array([0, 2, 1], dtype=int64))
