In [1]:
import numpy as np
array1 = np.random.randint(1, 10, 6)
print(array1)
print(np.where(array1 > 5, 1, -1))

[4 8 7 3 4 4]
[-1  1  1 -1 -1 -1]


In [2]:
np.where(array1 > 5)    # 获取满足条件得位置

(array([1, 2], dtype=int64),)

In [3]:
array1[np.where(array1 > 5)]

array([8, 7])

In [4]:
array2 = np.arange(6).reshape(2, 3)
print(array2)
print(np.argwhere(array2 % 2 == 0))
print(np.where(array2 % 2 == 0))

[[0 1 2]
 [3 4 5]]
[[0 0]
 [0 2]
 [1 1]]
(array([0, 0, 1], dtype=int64), array([0, 2, 1], dtype=int64))


In [5]:
arr01 = np.array([0, 1, 1, 3, 2, 1, 2, 2, 3, 3, 5])
print(np.bincount(arr01))       # [1 3 3 3 0 1]

[1 3 3 3 0 1]


In [6]:
print(np.bincount(arr01, minlength=3))          # [1 3 3 3 0 1]
print(np.bincount(arr01, minlength=8))          # [1 3 3 3 0 1 0 0]

[1 3 3 3 0 1]
[1 3 3 3 0 1 0 0]


In [8]:
arr02 = np.array([1, 2, 1, 2, 0])
weights = np.array([0.3, 0.5, 0.2, 0.7, -1.])
print(np.bincount(arr02, weights=weights))  #   [-1.   0.5  1.2]

[-1.   0.5  1.2]
